# Regenerate shell/window_icon.h from docs/images/logo-app.png.
#
#     powershell -ExecutionPolicy Bypass -File shell/make-window-icon.ps1
#
# window_icon.h is a COMMITTED, generated C header holding the SPRITESTEP mark as a 128x128 PNG,
# embedded as a byte array. It is decoded once at start-up and handed to SDL_SetWindowIcon so the
# window and taskbar entry carry the app icon on the platforms that have a window manager but do NOT
# read the icon out of the executable the way Windows does (desktop Linux especially). See the header
# of that call in shell/sdl-video.cpp.
#
# Why EMBEDDED rather than an asset file beside the exe: the Linux desktop build ships as a bare ELF
# with no packaging step, so there is nowhere to put a companion PNG for read_asset() to find. Baking
# the bytes into the binary is the Linux mirror of what the Windows .rc already does — the icon
# travels inside the one file the user actually runs. It is the SAME source image the Windows .ico is
# built from (docs/images/logo-app.png), so every platform shows one mark.
#
# This is not part of any build and CI never runs it — same contract as shell/windows/make-icon.ps1:
# the output is a derived artifact with a stated source, regenerated by hand when the logo changes.
#
# ⚠️ No ImageMagick, no Pillow. System.Drawing scales the source and encodes the PNG; the header is
# written out below as plain text. .ps1, because this is the Windows dev box (make-icon.ps1 too).

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$repo = Split-Path -Parent $PSScriptRoot
$src  = Join-Path $repo 'docs\images\logo-app.png'
$out  = Join-Path $PSScriptRoot 'window_icon.h'

# 128 is the sweet spot for a window icon: window managers draw it at 16-48px in a title bar and
# 32-64px in a taskbar / alt-tab, so 128 gives them headroom to downscale cleanly without bloating
# the binary the way the 256 frame would. One size only — SDL_SetWindowIcon takes a single surface
# and the WM does the rest.
$N = 128

$source = New-Object System.Drawing.Bitmap($src)
Write-Output ("source: {0}  {1}x{2}" -f (Split-Path -Leaf $src), $source.Width, $source.Height)

$bmp = New-Object System.Drawing.Bitmap($N, $N, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g   = [System.Drawing.Graphics]::FromImage($bmp)
$g.InterpolationMode  = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
$g.PixelOffsetMode    = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
$g.SmoothingMode      = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
$g.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
$g.DrawImage($source, (New-Object System.Drawing.Rectangle(0, 0, $N, $N)),
             0, 0, $source.Width, $source.Height, [System.Drawing.GraphicsUnit]::Pixel)
$g.Dispose()
$source.Dispose()

$ms = New-Object System.IO.MemoryStream
$bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
$bytes = $ms.ToArray()
Write-Output ("encoded: {0}x{0} PNG, {1:N0} bytes" -f $N, $bytes.Length)

# ─── Write the header ───────────────────────────────────────────────────────────────────────────
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// shell/window_icon.h - GENERATED by shell/make-window-icon.ps1. DO NOT EDIT.")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// The SPRITESTEP mark (docs/images/logo-app.png) as a ${N}x${N} PNG, embedded for")
[void]$sb.AppendLine("// SDL_SetWindowIcon on the platforms that do not read the icon out of the executable")
[void]$sb.AppendLine("// (desktop Linux). Decoded once at start-up in sdl-video.cpp. Regenerate with the .ps1.")
[void]$sb.AppendLine("#ifndef SPRITESTEP_WINDOW_ICON_H")
[void]$sb.AppendLine("#define SPRITESTEP_WINDOW_ICON_H")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const unsigned char kWindowIconPng[] = {")
$line = '    '
for ($i = 0; $i -lt $bytes.Length; $i++) {
    $line += ('0x{0:x2}, ' -f $bytes[$i])
    if (($i % 16) -eq 15) { [void]$sb.AppendLine($line.TrimEnd()); $line = '    ' }
}
if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line.TrimEnd()) }
[void]$sb.AppendLine('};')
[void]$sb.AppendLine("static const unsigned int kWindowIconPngLen = $($bytes.Length);")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#endif  // SPRITESTEP_WINDOW_ICON_H")
[System.IO.File]::WriteAllText($out, $sb.ToString())

# ─── Verify the FILE, not the loop that wrote it ────────────────────────────────────────────────
# Re-read the header off disk, pull the byte count back out of its declaration, and confirm it
# matches what was encoded. Cheap, and it catches a truncated write or an off-by-one in the emitter.
$text = [System.IO.File]::ReadAllText($out)
if ($text -notmatch 'kWindowIconPngLen = (\d+);') { throw "could not find kWindowIconPngLen in $out" }
$declared = [int]$Matches[1]
if ($declared -ne $bytes.Length) {
    throw "header declares $declared bytes but the PNG is $($bytes.Length)"
}
$commas = ([regex]::Matches($text, '0x[0-9a-f]{2},')).Count
if ($commas -ne $bytes.Length) {
    throw "header has $commas byte literals but the PNG is $($bytes.Length) bytes"
}
Write-Output ("wrote: {0}  ({1:N0} bytes, {2} literals == {3}-byte PNG)" -f `
              $out, (Get-Item $out).Length, $commas, $bytes.Length)
Write-Output "ok"
